export default {
  baseUrl: "https://cdn.jsdelivr.net/npm/prismjs@1.30.0",
  async setup({ loadScript }) {
    await loadScript(`${this.baseUrl}/components/prism-core.min.js`);
    await loadScript(
      `${this.baseUrl}/plugins/autoloader/prism-autoloader.min.js`
    );
    window.Prism.plugins.autoloader.languages_path = `${this.baseUrl}/components/`;
  },
  getThemeUrl(theme) {
    return `${this.baseUrl}/themes/${theme}.min.css`;
  },

  async highlight({ code, language }) {
    await new Promise((resolve, reject) =>
      window.Prism.plugins.autoloader.loadLanguages(language, resolve, reject)
    );

    const highlighted = window.Prism.highlight(
      code,
      window.Prism.languages[language],
      language
    );
    return `<pre class="language-${language}"><code class="language-${language}">${highlighted}</code></pre>`;
  },
  defaultTheme: "prism-tomorrow",
  themes: [
    { value: "prism", name: "Default" },
    { value: "prism-dark", name: "Dark" },
    { value: "prism-funky", name: "Funky" },
    { value: "prism-okaidia", name: "Okaidia" },
    { value: "prism-twilight", name: "Twilight" },
    { value: "prism-coy", name: "Coy" },
    { value: "prism-solarizedlight", name: "Solarized Light" },
    { value: "prism-tomorrow", name: "Tomorrow Night" },
  ],
  languages: [
    { value: "markup", name: "Markup (HTML, XML, SVG, MathML)" },
    { value: "css", name: "CSS" },
    { value: "clike", name: "C-like" },
    { value: "javascript", name: "JavaScript" },
    { value: "abap", name: "ABAP" },
    { value: "abnf", name: "ABNF" },
    { value: "actionscript", name: "ActionScript" },
    { value: "ada", name: "Ada" },
    { value: "agda", name: "Agda" },
    { value: "al", name: "AL" },
    { value: "antlr4", name: "ANTLR4" },
    { value: "apacheconf", name: "Apache Configuration" },
    { value: "apex", name: "Apex" },
    { value: "apl", name: "APL" },
    { value: "applescript", name: "AppleScript" },
    { value: "aql", name: "AQL" },
    { value: "arduino", name: "Arduino" },
    { value: "arff", name: "ARFF" },
    { value: "armasm", name: "ARM Assembly" },
    { value: "arturo", name: "Arturo" },
    { value: "asciidoc", name: "AsciiDoc" },
    { value: "aspnet", name: "ASP.NET (C#)" },
    { value: "asm6502", name: "6502 Assembly" },
    { value: "asmatmel", name: "Atmel AVR Assembly" },
    { value: "autohotkey", name: "AutoHotkey" },
    { value: "autoit", name: "AutoIt" },
    { value: "avisynth", name: "AviSynth" },
    { value: "avro-idl", name: "Avro IDL" },
    { value: "awk", name: "AWK" },
    { value: "bash", name: "Bash" },
    { value: "basic", name: "BASIC" },
    { value: "batch", name: "Batch" },
    { value: "bbcode", name: "BBcode" },
    { value: "bbj", name: "BBj" },
    { value: "bicep", name: "Bicep" },
    { value: "birb", name: "Birb" },
    { value: "bison", name: "Bison" },
    { value: "bnf", name: "BNF" },
    { value: "bqn", name: "BQN" },
    { value: "brainfuck", name: "Brainfuck" },
    { value: "brightscript", name: "BrightScript" },
    { value: "bro", name: "Bro" },
    { value: "bsl", name: "BSL (1C:Enterprise)" },
    { value: "c", name: "C" },
    { value: "csharp", name: "C#" },
    { value: "cpp", name: "C++" },
    { value: "cfscript", name: "CFScript" },
    { value: "chaiscript", name: "ChaiScript" },
    { value: "cil", name: "CIL" },
    { value: "cilkc", name: "Cilk/C" },
    { value: "cilkcpp", name: "Cilk/C++" },
    { value: "clojure", name: "Clojure" },
    { value: "cmake", name: "CMake" },
    { value: "cobol", name: "COBOL" },
    { value: "coffeescript", name: "CoffeeScript" },
    { value: "concurnas", name: "Concurnas" },
    { value: "csp", name: "Content-Security-Policy" },
    { value: "cooklang", name: "Cooklang" },
    { value: "coq", name: "Coq" },
    { value: "crystal", name: "Crystal" },
    { value: "css-extras", name: "CSS Extras" },
    { value: "csv", name: "CSV" },
    { value: "cue", name: "CUE" },
    { value: "cypher", name: "Cypher" },
    { value: "d", name: "D" },
    { value: "dart", name: "Dart" },
    { value: "dataweave", name: "DataWeave" },
    { value: "dax", name: "DAX" },
    { value: "dhall", name: "Dhall" },
    { value: "diff", name: "Diff" },
    { value: "django", name: "Django/Jinja2" },
    { value: "dns-zone-file", name: "DNS zone file" },
    { value: "docker", name: "Docker" },
    { value: "dot", name: "DOT (Graphviz)" },
    { value: "ebnf", name: "EBNF" },
    { value: "editorconfig", name: "EditorConfig" },
    { value: "eiffel", name: "Eiffel" },
    { value: "ejs", name: "EJS" },
    { value: "elixir", name: "Elixir" },
    { value: "elm", name: "Elm" },
    { value: "etlua", name: "Embedded Lua templating" },
    { value: "erb", name: "ERB" },
    { value: "erlang", name: "Erlang" },
    { value: "excel-formula", name: "Excel Formula" },
    { value: "fsharp", name: "F#" },
    { value: "factor", name: "Factor" },
    { value: "false", name: "False" },
    { value: "firestore-security-rules", name: "Firestore security rules" },
    { value: "flow", name: "Flow" },
    { value: "fortran", name: "Fortran" },
    { value: "ftl", name: "FreeMarker Template Language" },
    { value: "gml", name: "GameMaker Language" },
    { value: "gap", name: "GAP (CAS)" },
    { value: "gcode", name: "G-code" },
    { value: "gdscript", name: "GDScript" },
    { value: "gedcom", name: "GEDCOM" },
    { value: "gettext", name: "gettext" },
    { value: "gherkin", name: "Gherkin" },
    { value: "git", name: "Git" },
    { value: "glsl", name: "GLSL" },
    { value: "gn", name: "GN" },
    { value: "linker-script", name: "GNU Linker Script" },
    { value: "go", name: "Go" },
    { value: "go-module", name: "Go module" },
    { value: "gradle", name: "Gradle" },
    { value: "graphql", name: "GraphQL" },
    { value: "groovy", name: "Groovy" },
    { value: "haml", name: "Haml" },
    { value: "handlebars", name: "Handlebars" },
    { value: "haskell", name: "Haskell" },
    { value: "haxe", name: "Haxe" },
    { value: "hcl", name: "HCL" },
    { value: "hlsl", name: "HLSL" },
    { value: "hoon", name: "Hoon" },
    { value: "http", name: "HTTP" },
    { value: "hpkp", name: "HTTP Public-Key-Pins" },
    { value: "hsts", name: "HTTP Strict-Transport-Security" },
    { value: "ichigojam", name: "IchigoJam" },
    { value: "icon", name: "Icon" },
    { value: "icu-message-format", name: "ICU Message Format" },
    { value: "idris", name: "Idris" },
    { value: "ignore", name: ".ignore" },
    { value: "inform7", name: "Inform 7" },
    { value: "ini", name: "Ini" },
    { value: "io", name: "Io" },
    { value: "j", name: "J" },
    { value: "java", name: "Java" },
    { value: "javadoc", name: "JavaDoc" },
    { value: "javadoclike", name: "JavaDoc-like" },
    { value: "javastacktrace", name: "Java stack trace" },
    { value: "jexl", name: "Jexl" },
    { value: "jolie", name: "Jolie" },
    { value: "jq", name: "JQ" },
    { value: "jsdoc", name: "JSDoc" },
    { value: "js-extras", name: "JS Extras" },
    { value: "json", name: "JSON" },
    { value: "json5", name: "JSON5" },
    { value: "jsonp", name: "JSONP" },
    { value: "jsstacktrace", name: "JS stack trace" },
    { value: "js-templates", name: "JS Templates" },
    { value: "julia", name: "Julia" },
    { value: "keepalived", name: "Keepalived Configure" },
    { value: "keyman", name: "Keyman" },
    { value: "kotlin", name: "Kotlin" },
    { value: "kumir", name: "KuMir (КуМир)" },
    { value: "kusto", name: "Kusto" },
    { value: "latex", name: "LaTeX" },
    { value: "latte", name: "Latte" },
    { value: "less", name: "Less" },
    { value: "lilypond", name: "LilyPond" },
    { value: "liquid", name: "Liquid" },
    { value: "lisp", name: "Lisp" },
    { value: "livescript", name: "LiveScript" },
    { value: "llvm", name: "LLVM IR" },
    { value: "log", name: "Log file" },
    { value: "lolcode", name: "LOLCODE" },
    { value: "lua", name: "Lua" },
    { value: "magma", name: "Magma (CAS)" },
    { value: "makefile", name: "Makefile" },
    { value: "markdown", name: "Markdown" },
    { value: "markup-templating", name: "Markup templating" },
    { value: "mata", name: "Mata" },
    { value: "matlab", name: "MATLAB" },
    { value: "maxscript", name: "MAXScript" },
    { value: "mel", name: "MEL" },
    { value: "mermaid", name: "Mermaid" },
    { value: "metafont", name: "METAFONT" },
    { value: "mizar", name: "Mizar" },
    { value: "mongodb", name: "MongoDB" },
    { value: "monkey", name: "Monkey" },
    { value: "moonscript", name: "MoonScript" },
    { value: "n1ql", name: "N1QL" },
    { value: "n4js", name: "N4JS" },
    { value: "nand2tetris-hdl", name: "Nand To Tetris HDL" },
    { value: "naniscript", name: "Naninovel Script" },
    { value: "nasm", name: "NASM" },
    { value: "neon", name: "NEON" },
    { value: "nevod", name: "Nevod" },
    { value: "nginx", name: "nginx" },
    { value: "nim", name: "Nim" },
    { value: "nix", name: "Nix" },
    { value: "nsis", name: "NSIS" },
    { value: "objectivec", name: "Objective-C" },
    { value: "ocaml", name: "OCaml" },
    { value: "odin", name: "Odin" },
    { value: "opencl", name: "OpenCL" },
    { value: "openqasm", name: "OpenQasm" },
    { value: "oz", name: "Oz" },
    { value: "parigp", name: "PARI/GP" },
    { value: "parser", name: "Parser" },
    { value: "pascal", name: "Pascal" },
    { value: "pascaligo", name: "Pascaligo" },
    { value: "psl", name: "PATROL Scripting Language" },
    { value: "pcaxis", name: "PC-Axis" },
    { value: "peoplecode", name: "PeopleCode" },
    { value: "perl", name: "Perl" },
    { value: "php", name: "PHP" },
    { value: "phpdoc", name: "PHPDoc" },
    { value: "php-extras", name: "PHP Extras" },
    { value: "plant-uml", name: "PlantUML" },
    { value: "plsql", name: "PL/SQL" },
    { value: "powerquery", name: "PowerQuery" },
    { value: "powershell", name: "PowerShell" },
    { value: "processing", name: "Processing" },
    { value: "prolog", name: "Prolog" },
    { value: "promql", name: "PromQL" },
    { value: "properties", name: ".properties" },
    { value: "protobuf", name: "Protocol Buffers" },
    { value: "pug", name: "Pug" },
    { value: "puppet", name: "Puppet" },
    { value: "pure", name: "Pure" },
    { value: "purebasic", name: "PureBasic" },
    { value: "purescript", name: "PureScript" },
    { value: "python", name: "Python" },
    { value: "qsharp", name: "Q#" },
    { value: "q", name: "Q (kdb+ database)" },
    { value: "qml", name: "QML" },
    { value: "qore", name: "Qore" },
    { value: "r", name: "R" },
    { value: "racket", name: "Racket" },
    { value: "cshtml", name: "Razor C#" },
    { value: "jsx", name: "React JSX" },
    { value: "tsx", name: "React TSX" },
    { value: "reason", name: "Reason" },
    { value: "regex", name: "Regex" },
    { value: "rego", name: "Rego" },
    { value: "renpy", name: "Ren'py" },
    { value: "rescript", name: "ReScript" },
    { value: "rest", name: "reST (reStructuredText)" },
    { value: "rip", name: "Rip" },
    { value: "roboconf", name: "Roboconf" },
    { value: "robotframework", name: "Robot Framework" },
    { value: "ruby", name: "Ruby" },
    { value: "rust", name: "Rust" },
    { value: "sas", name: "SAS" },
    { value: "sass", name: "Sass (Sass)" },
    { value: "scss", name: "Sass (SCSS)" },
    { value: "scala", name: "Scala" },
    { value: "scheme", name: "Scheme" },
    { value: "shell-session", name: "Shell session" },
    { value: "smali", name: "Smali" },
    { value: "smalltalk", name: "Smalltalk" },
    { value: "smarty", name: "Smarty" },
    { value: "sml", name: "SML" },
    { value: "solidity", name: "Solidity (Ethereum)" },
    { value: "solution-file", name: "Solution file" },
    { value: "soy", name: "Soy (Closure Template)" },
    { value: "sparql", name: "SPARQL" },
    { value: "splunk-spl", name: "Splunk SPL" },
    { value: "sqf", name: "SQF: Status Quo Function (Arma 3)" },
    { value: "sql", name: "SQL" },
    { value: "squirrel", name: "Squirrel" },
    { value: "stan", name: "Stan" },
    { value: "stata", name: "Stata Ado" },
    { value: "iecst", name: "Structured Text (IEC 61131-3)" },
    { value: "stylus", name: "Stylus" },
    { value: "supercollider", name: "SuperCollider" },
    { value: "swift", name: "Swift" },
    { value: "systemd", name: "Systemd configuration file" },
    { value: "t4-templating", name: "T4 templating" },
    { value: "t4-cs", name: "T4 Text Templates (C#)" },
    { value: "t4-vb", name: "T4 Text Templates (VB)" },
    { value: "tap", name: "TAP" },
    { value: "tcl", name: "Tcl" },
    { value: "tt2", name: "Template Toolkit 2" },
    { value: "textile", name: "Textile" },
    { value: "toml", name: "TOML" },
    { value: "tremor", name: "Tremor" },
    { value: "turtle", name: "Turtle" },
    { value: "twig", name: "Twig" },
    { value: "typescript", name: "TypeScript" },
    { value: "typoscript", name: "TypoScript" },
    { value: "unrealscript", name: "UnrealScript" },
    { value: "uorazor", name: "UO Razor Script" },
    { value: "uri", name: "URI" },
    { value: "v", name: "V" },
    { value: "vala", name: "Vala" },
    { value: "vbnet", name: "VB.Net" },
    { value: "velocity", name: "Velocity" },
    { value: "verilog", name: "Verilog" },
    { value: "vhdl", name: "VHDL" },
    { value: "vim", name: "vim" },
    { value: "visual-basic", name: "Visual Basic" },
    { value: "warpscript", name: "WarpScript" },
    { value: "wasm", name: "WebAssembly" },
    { value: "web-idl", name: "Web IDL" },
    { value: "wgsl", name: "WGSL" },
    { value: "wiki", name: "Wiki markup" },
    { value: "wolfram", name: "Wolfram language" },
    { value: "wren", name: "Wren" },
    { value: "xeora", name: "Xeora" },
    { value: "xml-doc", name: "XML doc (.net)" },
    { value: "xojo", name: "Xojo (REALbasic)" },
    { value: "xquery", name: "XQuery" },
    { value: "yaml", name: "YAML" },
    { value: "yang", name: "YANG" },
    { value: "zig", name: "Zig" },
  ],
};
