import Alpine from "https://cdn.jsdelivr.net/npm/alpinejs@3.14.9/+esm";

const APP_URL = "https://psd-coder.github.io/code-to-markup/";
const FALLBACK_HIGHLIGHTER = "shiki";
const FALLBACK_LANGUAGE = "yaml";
const FALLBACK_THEME = "github-dark";
const STATE_TO_SEARCH_PARAMS = { highlighter: "h", theme: "t", language: "l" };
const HIGHLIGHTERS = {
  shiki: {
    name: "Shiki",
    file: "./highlighters/shiki.mjs",
  },
  highlight: {
    name: "Highlight.js",
    file: "./highlighters/highlight.mjs",
  },
  prism: {
    name: "Prism.js",
    file: "./highlighters/prism.mjs",
  },
};

const INITIAL_CODE = `# lefthook.yml

# Build commit messages
prepare-commit-msg:
  commands:
    commitzen:
      interactive: true
      run: yarn run cz --hook
      env:
        LEFTHOOK: 0

# Validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: yarn run commitlint --edit {1}`;

main();

function main() {
  const HIGHLIGHTER_STATE = { IDLE: 0, INITILIZING: 1, HIGHLIGHTING: 2 };
  const LOADING_STATE = { OK: 0, LOADING: 1, FAILED: 2 };

  Alpine.data("app", () => {
    const initialState = getInitialState(Object.keys(HIGHLIGHTERS), {
      highlighter: FALLBACK_HIGHLIGHTER,
      theme: FALLBACK_THEME,
      language: FALLBACK_LANGUAGE,
      code: INITIAL_CODE,
    });

    return {
      HIGHLIGHTER_STATE,
      LOADING_STATE,
      highlighters: Object.entries(HIGHLIGHTERS).reduce((acc, [id, data]) => {
        acc[id] = {
          ...data,
          module: null,
          initialized: false,
          setupPromise: null,
        };
        return acc;
      }, {}),
      highlighterState: HIGHLIGHTER_STATE.IDLE,
      themeLoadingState: LOADING_STATE.OK,
      languageLoadingState: LOADING_STATE.OK,
      state: initialState,
      highlightedCode: "",

      get currentHighlighter() {
        return (
          this.highlighters[this.state.highlighter].module ??
          getHighlighterFallback(initialState)
        );
      },

      get currentThemeCssUrl() {
        return this.currentHighlighter.getThemeUrl(this.state.theme);
      },

      get cssStyles() {
        return (
          this.currentThemeCssUrl &&
          `<link rel="stylesheet" href="${this.currentThemeCssUrl}">`
        );
      },

      get cssSize() {
        return (
          this.currentThemeCssUrl && getCSSFileSize(this.currentThemeCssUrl)
        );
      },

      get isProcessing() {
        return (
          this.highlighterState !== HIGHLIGHTER_STATE.IDLE ||
          this.themeLoadingState === LOADING_STATE.LOADING ||
          this.languageLoadingState === LOADING_STATE.LOADING
        );
      },

      get fallbackHighlightedMessage() {
        if (this.highlighterState === HIGHLIGHTER_STATE.INITILIZING) {
          return "Loading highlighter...";
        }

        if (this.themeLoadingState === LOADING_STATE.FAILED) {
          return `Failed to load theme "${this.state.theme}". Please check your internet connection or try a different theme.`;
        }

        if (this.languageLoadingState === LOADING_STATE.FAILED) {
          return `Failed to load language "${this.state.language}". Please check your internet connection or try a different language.`;
        }

        if (this.languageLoadingState === LOADING_STATE.LOADING) {
          return `Loading language "${this.state.language}"...`;
        }

        if (this.themeLoadingState === LOADING_STATE.LOADING) {
          return `Loading theme "${this.state.theme}"...`;
        }

        if (this.highlighterState === HIGHLIGHTER_STATE.HIGHLIGHTING) {
          return "Highlighting code...";
        }

        return "Highlighted code will appear here...";
      },

      getHighligtedCodeForCopying() {
        return `<!-- Code is generated by Code to Markup. Go there if you want to update it: ${APP_URL}${getURL(
          this.state,
          false
        )} -->\n${this.highlightedCode}`;
      },

      async init() {
        await this.ensureHighlighterInitialized(this.state.highlighter);
        this.highlightCode();
      },

      async ensureHighlighterInitialized(id) {
        if (!this.highlighters[id].initialized) {
          this.highlighterState = this.HIGHLIGHTER_STATE.INITILIZING;
          const module = await import(this.highlighters[id].file).then(
            ({ default: module }) => module
          );

          this.highlighters[id].module = module;
          this.highlighters[id].setupPromise = module.setup({
            loadScript,
          });
          this.highlighters[id].setupPromise.then(() => {
            this.highlighterState = this.HIGHLIGHTER_STATE.IDLE;
          });
        }

        return this.highlighters[id].setupPromise;
      },

      async updateURLAndHighlight(options) {
        updateURLAndLocalStorage(this.state);
        return this.highlightCode(options);
      },

      async highlightCode(options) {
        const opts = Object.assign({}, { toggleLoadingState: true }, options);

        if (!this.state.code.trim()) {
          this.highlightedCode = "";
          return;
        }

        if (opts.toggleLoadingState) {
          this.isHighlighting = true;
        }

        this.highlightedCode = await this.currentHighlighter.highlight({
          ...this.state,
          loadScript,
        });

        if (opts.toggleLoadingState) {
          this.isHighlighting = false;
        }
      },

      async onHighlighterChange(event) {
        await this.ensureHighlighterInitialized(event.target.value);
        this.state.highlighter = event.target.value;
        this.state.theme = this.currentHighlighter.themes.find(
          (t) => t.value === this.state.theme
        )
          ? this.state.theme
          : this.currentHighlighter.defaultTheme;
        this.state.language = this.currentHighlighter.languages.find(
          (l) => l.value === this.state.language
        )
          ? this.state.language
          : this.currentHighlighter.languages[0].value;
        this.updateURLAndHighlight();
      },

      async onThemeChange(event) {
        this.state.theme = event.target.value;
        this.handleThemeChange();
      },

      async handleThemeChange() {
        try {
          this.themeLoadingState = LOADING_STATE.LOADING;
          if (this.currentThemeCssUrl) {
            // Prefetch the CSS to ensure it's ready
            await fetch(this.currentThemeCssUrl);
          }
          this.updateURLAndHighlight();
          this.themeLoadingState = LOADING_STATE.OK;
        } catch {
          console.log("Failed to load theme:", this.state.theme);
          this.themeLoadingState = LOADING_STATE.FAILED;
        }
      },

      async onLanguageChange(event) {
        this.state.language = event.target.value;
        this.handleLanguageChange();
      },

      async handleLanguageChange() {
        try {
          this.languageLoadingState = LOADING_STATE.LOADING;
          this.updateURLAndHighlight();
          this.languageLoadingState = LOADING_STATE.OK;
        } catch {
          console.log("Failed to load language:", this.state.language);
          this.languageLoadingState = LOADING_STATE.FAILED;
        }
      },

      onCodeChange(event) {
        this.state.code = event.target.value;
        this.updateURLAndHighlight({ toggleLoadingState: false });
      },
    };
  });

  Alpine.data("copyButton", () => ({
    isCopying: false,
    async copy(data) {
      if (!data.trim()) {
        return;
      }

      this.isCopying = true;

      if (!navigator.clipboard.write) {
        await navigator.clipboard.writeText(data);
      } else {
        const itemRecords = { "text/plain": data };

        if (this.$el.hasAttribute("data-as-html")) {
          itemRecords["text/html"] = data;
        }

        await navigator.clipboard.write([new ClipboardItem(itemRecords)]);
      }

      setTimeout(() => {
        this.isCopying = false;
      }, 2000);
    },
  }));

  Alpine.start();
}

function loadScript(src) {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) {
      resolve();
      return;
    }

    const script = document.createElement("script");
    script.src = src;
    script.onload = resolve;
    script.onerror = () => reject(new Error(`Failed to load script: ${src}`));
    document.head.appendChild(script);
  });
}

async function getCSSFileSize(url) {
  try {
    const response = await fetch(url, { method: "HEAD" });
    const size = response.headers.get("Content-Length");

    if (size) {
      const formatter = Intl.NumberFormat("en", {
        notation: "compact",
        style: "unit",
        unit: "byte",
        unitDisplay: "narrow",
      });

      return formatter.format(size);
    }
  } catch (error) {
    console.warn("Could not fetch CSS size:", error);
  }

  return "Unknown";
}

function getHighlighterFallback(initial) {
  return {
    baseUrl: "",
    getThemeUrl() {
      return null;
    },
    setup() {},
    highlight() {},
    defaultTheme: initial.theme,
    themes: [{ value: initial.theme, name: "" }],
    languages: [{ value: initial.language, name: "" }],
  };
}

function getInitialState(availableHighlighters, fallback) {
  const urlParams = new URLSearchParams(window.location.search);
  const initialState = { code: "" };

  try {
    initialState.code = urlSafeAtob(window.location.hash.slice(1));
  } catch {}

  Object.keys(STATE_TO_SEARCH_PARAMS).forEach((key) => {
    let value =
      urlParams.get(STATE_TO_SEARCH_PARAMS[key]) ||
      window.localStorage.getItem(key);

    // Use fallback if unsupported highlighter is specified
    if (
      key === "highlighter" &&
      value &&
      !availableHighlighters.includes(value)
    ) {
      value = null;
    }

    initialState[key] = value || fallback[key];
  });

  // If code is not specified, use our fallback code for the selected language
  if (!initialState.code) {
    initialState.code = fallback.code;
    initialState.language = fallback.language;
  }

  return initialState;
}

function updateURLAndLocalStorage(state) {
  Object.keys(STATE_TO_SEARCH_PARAMS).forEach((key) => {
    window.localStorage.setItem(key, state[key]);
  });

  window.history.replaceState(null, "", getURL(state));
}

function getURL({ code, ...searchParamsState }, withCode = true) {
  const params = new URLSearchParams();

  Object.keys(STATE_TO_SEARCH_PARAMS).forEach((key) => {
    params.set(STATE_TO_SEARCH_PARAMS[key], searchParamsState[key]);
  });

  return `?${params.toString()}#${withCode ? urlSafeBtoa(code) : ""}`;
}

function urlSafeAtob(urlSafeB64) {
  const b64 = urlSafeB64
    .replaceAll("-", "+")
    .replaceAll("_", "/")
    .padEnd(Math.ceil(urlSafeB64.length / 4) * 4, "=");

  return atob(b64);
}

function urlSafeBtoa(data) {
  return btoa(data)
    .replaceAll("=", "")
    .replaceAll("+", "-")
    .replaceAll("/", "_");
}
