import Alpine from "https://cdnjs.cloudflare.com/ajax/libs/alpinejs/3.14.1/module.esm.min.js";

const APP_URL = "https://psd-coder.github.io/code-to-markup/";
const FALLBACK_HIGHLIGHTER = "highlight";
const FALLBACK_LANGUAGE = "yaml";
const FALLBACK_THEME = "night-owl";
const STATE_TO_SEARCH_PARAMS = { highlighter: "h", theme: "t", language: "l" };
const HIGHLIGHTERS = {
  highlight: {
    name: "Highlight.js",
    file: "./highlighters/highlight.mjs",
    module: null,
    setupPromise: null,
  },
  prism: {
    name: "Prism.js",
    file: "./highlighters/prism.mjs",
    module: null,
    setupPromise: null,
  },
  shiki: {
    name: "Shiki",
    file: "./highlighters/shiki.mjs",
    module: null,
    setupPromise: null,
  },
};

const INITIAL_CODE = `# lefthook.yml

# Build commit messages
prepare-commit-msg:
  commands:
    commitzen:
      interactive: true
      run: yarn run cz --hook
      env:
        LEFTHOOK: 0

# Validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: yarn run commitlint --edit {1}`;

main();

function main() {
  Alpine.data("app", () => {
    const initialState = getInitialState(Object.keys(HIGHLIGHTERS), {
      highlighter: FALLBACK_HIGHLIGHTER,
      theme: FALLBACK_THEME,
      language: FALLBACK_LANGUAGE,
      code: INITIAL_CODE,
    });

    return {
      isInitializingHightlighter: false,
      isLoadingTheme: false,
      isHighlighting: false,
      highlighters: HIGHLIGHTERS,
      state: initialState,
      highlightedCode: "",

      get currentHighlighter() {
        return (
          this.highlighters[this.state.highlighter].module ??
          getHighlighterFallback(initialState)
        );
      },

      get currentThemeCssUrl() {
        return this.currentHighlighter.getThemeUrl(this.state.theme);
      },

      get cssStyles() {
        return (
          this.currentThemeCssUrl &&
          `<link rel="stylesheet" href="${this.currentThemeCssUrl}">`
        );
      },

      get cssSize() {
        return (
          this.currentThemeCssUrl && getCSSFileSize(this.currentThemeCssUrl)
        );
      },

      get isProcessing() {
        return (
          this.isInitializingHightlighter ||
          this.isLoadingTheme ||
          this.isHighlighting
        );
      },

      get fallbackHighlightedMessage() {
        if (this.isInitializingHightlighter) {
          return "Loading highlighter...";
        }

        if (this.isHighlighting) {
          return "Highlighting code...";
        }

        if (this.isLoadingTheme) {
          return "Loading theme...";
        }

        return "Highlighted code will appear here...";
      },

      getHighligtedCodeForCopying() {
        return `<!-- Code is generated by Code to Markup. Go there if you want to update it: ${APP_URL}${getURL(
          this.state,
          false
        )} -->\n${this.highlightedCode}`;
      },

      async init() {
        await this.ensureHighlighterInitialized(this.state.highlighter);
        this.highlightCode();
      },

      async ensureHighlighterInitialized(id) {
        if (!this.highlighters[id].initialized) {
          this.isInitializingHightlighter = true;
          const module = await import(this.highlighters[id].file).then(
            ({ default: module }) => module
          );

          // If selected theme or language is not available, set to defaults
          if (!module.themes.find((t) => t.value === this.state.theme)) {
            this.state.theme = module.defaultTheme;
          }
          if (!module.languages.find((l) => l.value === this.state.language)) {
            this.state.language = module.languages[0].value;
          }

          this.highlighters[id].module = module;
          this.highlighters[id].setupPromise = module.setup({
            loadScript,
          });
          this.highlighters[id].setupPromise.then(() => {
            this.isInitializingHightlighter = false;
          });
        }

        return this.highlighters[id].setupPromise;
      },

      async updateURLAndHighlight() {
        updateURLAndLocalStorage(this.state);
        return this.highlightCode();
      },

      async highlightCode() {
        if (!this.state.code.trim()) {
          this.highlightedCode = "";
          return;
        }

        this.isHighlighting = true;
        this.highlightedCode = await this.currentHighlighter.highlight({
          ...this.state,
          loadScript,
        });
        this.isHighlighting = false;
      },

      async onHighlighterChange(event) {
        await this.ensureHighlighterInitialized(event.target.value);
        this.state.highlighter = event.target.value;
        this.state.theme = this.currentHighlighter.defaultTheme;
        this.state.language = this.currentHighlighter.languages.find(
          (l) => l.value === this.state.language
        )
          ? this.state.language
          : this.currentHighlighter.languages[0].value;
        this.updateURLAndHighlight();
      },

      async onThemeChange(event) {
        this.state.theme = event.target.value;

        if (this.currentThemeCssUrl) {
          this.isLoadingTheme = true;
          // Prefetch the CSS to ensure it's ready
          await fetch(this.currentThemeCssUrl);
          this.isLoadingTheme = false;
        }

        this.updateURLAndHighlight();
      },

      onLanguageChange(event) {
        this.state.language = event.target.value;
        this.updateURLAndHighlight();
      },

      onCodeChange(event) {
        this.state.code = event.target.value;
        this.updateURLAndHighlight();
      },
    };
  });

  Alpine.data("copyButton", () => ({
    isCopying: false,
    async copy(data) {
      if (!data.trim()) {
        return;
      }

      this.isCopying = true;
      await navigator.clipboard.writeText(data);

      setTimeout(() => {
        this.isCopying = false;
      }, 2000);
    },
  }));

  Alpine.start();
}

function loadScript(src) {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) {
      resolve();
      return;
    }

    const script = document.createElement("script");
    script.src = src;
    script.onload = resolve;
    script.onerror = () => reject(new Error(`Failed to load script: ${src}`));
    document.head.appendChild(script);
  });
}

async function getCSSFileSize(url) {
  try {
    const response = await fetch(url, { method: "HEAD" });
    const size = response.headers.get("Content-Length");

    if (size) {
      const formatter = Intl.NumberFormat("en", {
        notation: "compact",
        style: "unit",
        unit: "byte",
        unitDisplay: "narrow",
      });

      return formatter.format(size);
    }
  } catch (error) {
    console.warn("Could not fetch CSS size:", error);
  }

  return "Unknown";
}

function getHighlighterFallback(initial) {
  return {
    baseUrl: "",
    getThemeUrl() {
      return null;
    },
    setup() {},
    highlight() {},
    defaultTheme: initial.theme,
    themes: [{ value: initial.theme, name: "" }],
    languages: [{ value: initial.language, name: "" }],
  };
}

function getInitialState(availableHighlighters, fallback) {
  const urlParams = new URLSearchParams(window.location.search);
  const initialState = {};

  Object.keys(STATE_TO_SEARCH_PARAMS).forEach((key) => {
    let searchParam = urlParams.get(STATE_TO_SEARCH_PARAMS[key]);

    if (
      searchParam &&
      key === "highlighter" &&
      !availableHighlighters.includes(searchParam)
    ) {
      searchParam = null;
    }

    initialState[key] =
      searchParam || window.localStorage.getItem(key) || fallback[key];
  });

  const codeHash = window.location.hash.slice(1);
  initialState.code = codeHash
    ? urlSafeAtob(codeHash)
    : window.localStorage.getItem("code") || fallback.code;

  return initialState;
}

function updateURLAndLocalStorage(state) {
  Object.keys(STATE_TO_SEARCH_PARAMS).forEach((key) => {
    window.localStorage.setItem(key, state[key]);
  });

  window.history.replaceState(null, "", getURL(state));
}

function getURL({ code, ...searchParamsState }, withCode = true) {
  const params = new URLSearchParams();

  Object.keys(STATE_TO_SEARCH_PARAMS).forEach((key) => {
    params.set(STATE_TO_SEARCH_PARAMS[key], searchParamsState[key]);
  });

  return `?${params.toString()}#${withCode ? urlSafeBtoa(code) : ""}`;
}

function urlSafeAtob(urlSafeB64) {
  const b64 = urlSafeB64
    .replaceAll("-", "+")
    .replaceAll("_", "/")
    .padEnd(Math.ceil(urlSafeB64.length / 4) * 4, "=");

  return atob(b64);
}

function urlSafeBtoa(data) {
  return btoa(data)
    .replaceAll("=", "")
    .replaceAll("+", "-")
    .replaceAll("/", "_");
}
